# Generated by Django 5.1.1 on 2024-10-13 09:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Название категории статьи')),
                ('cat_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('cat_metadesc', models.CharField(blank=True, max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('cat_slug', models.CharField(default='slug2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('cat_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('cat_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение категории')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Название категории кейсов')),
                ('cat_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('cat_metadesc', models.CharField(blank=True, max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('cat_slug', models.CharField(default='slug2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('cat_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('cat_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение категории')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Название категории вебинаров')),
                ('cat_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('cat_metadesc', models.CharField(blank=True, max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('cat_slug', models.CharField(default='slug2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('cat_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('cat_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение категории')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=200, verbose_name='Название отзыва')),
                ('rewiew_person', models.CharField(max_length=200, verbose_name='Автор персона')),
                ('rewiew_job', models.CharField(max_length=200, verbose_name='Автор должность')),
                ('rewiew_company', models.CharField(max_length=200, verbose_name='Автор компания')),
                ('rewiew_text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rewiew_image', models.ImageField(upload_to='', verbose_name='Скан отзыва')),
                ('review_video', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на видео')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_name', models.CharField(max_length=200, verbose_name='Заголовок H1')),
                ('tweet_slug', models.CharField(default='article2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('tweet_short_desc', models.TextField(blank=True, verbose_name='Короткое описание для Schema')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('tweet_type', models.CharField(blank=True, choices=[('Вебинар', 'Вебинар'), ('Новость', 'Новость'), ('Заметка', 'Заметка'), ('Внимание', 'Внимание')], max_length=10, verbose_name='Тип заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='Заголовок H1')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('article_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('article_slug', models.CharField(default='article2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('article_short_desc', models.TextField(blank=True, verbose_name='Короткое описание для Schema')),
                ('article_image', models.ImageField(upload_to='', verbose_name='Изображение статьи')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category_article', models.ManyToManyField(blank=True, to='bitrixsite.articlecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='Заголовок H1')),
                ('case_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('case_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('case_slug', models.CharField(default='article2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('case_short_desc', models.TextField(blank=True, verbose_name='Короткое описание для Schema')),
                ('case_image', models.ImageField(upload_to='', verbose_name='Изображение кейса')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category_case', models.ManyToManyField(blank=True, to='bitrixsite.casecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('person_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('person_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('person_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('person_image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_name', models.CharField(max_length=200, verbose_name='Название')),
                ('webinar_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('webinar_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('webinar_slug', models.CharField(default='article2024-10-13 12:11:05.923989', max_length=200, verbose_name='URL')),
                ('webinar_image', models.ImageField(upload_to='', verbose_name='Изображение вебинара')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category_web', models.ManyToManyField(blank=True, to='bitrixsite.categorywebinar')),
                ('persons_web', models.ManyToManyField(blank=True, to='bitrixsite.person')),
            ],
        ),
    ]
