# Generated by Django 5.1.1 on 2025-01-08 09:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixsite', '0003_case_case_text_alter_article_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_client',
            field=models.TextField(blank=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_duration',
            field=models.TextField(blank=True, verbose_name='Временные затраты'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2025-01-08 12:12:18.922016', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 12:12:18.922016', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_slug',
            field=models.CharField(default='article2025-01-08 12:12:18.923521', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 12:12:18.923015', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categorywebinar',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 12:12:18.923521', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2025-01-08 12:12:18.920775', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='webinar_slug',
            field=models.CharField(default='article2025-01-08 12:12:18.923521', max_length=200, verbose_name='URL'),
        ),
    ]
