# Generated by Django 5.1.1 on 2025-01-08 10:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixsite', '0005_alter_article_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2025-01-08 13:21:10.549440', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 13:21:10.549440', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_slug',
            field=models.CharField(default='article2025-01-08 13:21:10.550948', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 13:21:10.549440', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categorywebinar',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-08 13:21:10.550948', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2025-01-08 13:21:10.548439', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='webinar_slug',
            field=models.CharField(default='article2025-01-08 13:21:10.551959', max_length=200, verbose_name='URL'),
        ),
    ]
