# Generated by Django 5.1.1 on 2025-01-27 12:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixsite', '0006_article_article_text_alter_article_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='webinar_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2025-01-27 15:41:09.030768', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 15:41:09.030768', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_slug',
            field=models.CharField(default='article2025-01-27 15:41:09.031271', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 15:41:09.031271', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categorywebinar',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 15:41:09.032276', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2025-01-27 15:41:09.029302', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='webinar_slug',
            field=models.CharField(default='article2025-01-27 15:41:09.032782', max_length=200, verbose_name='URL'),
        ),
    ]
