# Generated by Django 5.1.1 on 2025-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixsite', '0007_person_person_desc_webinar_webinar_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='webinar_short_desc',
            field=models.TextField(blank=True, verbose_name='Короткое описание для карточки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2025-01-27 17:17:49.993550', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 17:17:49.993550', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_slug',
            field=models.CharField(default='article2025-01-27 17:17:49.994644', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 17:17:49.994644', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categorywebinar',
            name='cat_slug',
            field=models.CharField(default='slug2025-01-27 17:17:49.995655', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_slug',
            field=models.CharField(default='article2025-01-27 17:17:49.992546', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='webinar_slug',
            field=models.CharField(default='article2025-01-27 17:17:49.995655', max_length=200, verbose_name='URL'),
        ),
    ]
